CommonError: Add support for condition data
This is used for example to advertise a new MUC after destruction

<gone>xmpp:new@chat.example.org?join</gone>